//! OakRTB Rust SDK: prost-based protobuf models, JSON Schema validation, builders, views, and bid checks.
//!
//! - [`jsonschema`]: JSON Schema contract validation (optional on hot paths)
//! - [`codec`]: OpenRTB JSON encoding and decoding
//! - [`validation`]: basic model checks, format readiness, and shared diagnostic results
//! - [`builder`]: fluent builders for strongly typed models
//! - [`view`]: strongly typed BidRequest/BidResponse query views
//! - [`bidcheck`]: bid-to-request auction constraint checks (separate from Schema and basic validation)
//! - [`proto`]: generated protobuf messages (`oakrtb.v2`)

pub mod bidcheck;
pub mod builder;
pub mod codec;
#[cfg(feature = "jsonschema")]
pub mod jsonschema;
mod model_json;
pub mod validation;
pub mod view;

/// Protobuf messages generated by build.rs (`oakrtb.v2` package).
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/oakrtb.v2.rs"));
}

#[cfg(test)]
mod presence_tests {
    use super::proto::{BidResponse, Geo, Regs};
    use prost::Message;

    #[test]
    fn explicit_zero_survives_protobuf() {
        let regs = Regs {
            gdpr: Some(0),
            coppa: Some(0),
            ..Default::default()
        };
        let decoded = Regs::decode(regs.encode_to_vec().as_slice()).unwrap();
        assert_eq!(decoded.gdpr, Some(0));
        assert_eq!(decoded.coppa, Some(0));
        assert_eq!(Regs::decode(&[][..]).unwrap().gdpr, None);
        let geo = Geo {
            lat: Some(0.0),
            lon: Some(0.0),
            ..Default::default()
        };
        let decoded = Geo::decode(geo.encode_to_vec().as_slice()).unwrap();
        assert_eq!(decoded.lat, Some(0.0));
        assert_eq!(decoded.lon, Some(0.0));
        let response = BidResponse {
            nbr: Some(0),
            ..Default::default()
        };
        assert_eq!(
            BidResponse::decode(response.encode_to_vec().as_slice())
                .unwrap()
                .nbr,
            Some(0)
        );
    }
}
